server:
  port: 8095
jwt:
  secret: ${KEYSECRET_SECURITY:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}

spring:
  application:
    name: FOOD-COURT-SERVICE
  datasource:
    url: jdbc:mysql://localhost/food-court
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"